sudo: false

language: elm
node_js: '10'

cache:
  directories:
    - cache
    - sysconfcpus
    - node_modules
    - elm-stuff/build-artifacts

install:
  - make install

before_script:
  - "export NODE_OPTIONS=--max_old_space_size=4096"

script:
  - make clean setup build

deploy:
  provider: pages
  local_dir: dist
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: develop
