name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Restore cached Primes
        id: cache-generated-elm-modules-restore
        uses: actions/cache/restore@v3
        with:
          path: cache
          key: ${{ runner.os }}-generated-elm-modules
      - run: make install
      - run: make clean setup build
      - name: Save Primes
        id: cache-generated-elm-modules-save
        uses: actions/cache/save@v3
        with:
          path: cache
          key: ${{ steps.cache-generated-elm-modules-restore.outputs.cache-primary-key }}
